# Generated by Django 2.0.2 on 2019-07-23 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='event',
            field=models.CharField(max_length=200),
        ),
    ]
